In [16]:
import pandas as pd
import numpy as np

new_file = pd.read_csv('analysis_covid-19/result_entities_covid-19.tsv',delimiter='\t',on_bad_lines='warn')
print(np.sum(new_file['total_count']))
new_file

1610695

,Unnamed: 0,total_count,articles_spanned,batches_spanned,freq_per_article,freq_per_batch,batch_set,batch_count,articles_set
0,COVID 19,1168839,377771,754,3.094041,1550.184350,7; 8; 9; 10; 11; 12; 13; 14; 15; 16; 17; 18; 1...,"{7: 4, 8: 11, 9: 30, 10: 37, 11: 31, 12: 49, 1...",829cy3xl; qpf52vrx; lzd9lil6; n9pfxv7d; zyn8p6...
1,coronavirus disease,74663,69357,748,1.076503,99.816845,8; 9; 10; 11; 12; 14; 16; 17; 18; 19; 20; 22; ...,"{8: 1, 9: 4, 10: 1, 11: 3, 12: 2, 14: 2, 16: 1...",yg9ye3i2; kjfqdfen; nnhf3crw; 5p00bwej; o19kew...
2,coronavirus disease 2019,58002,53739,746,1.079328,77.750670,8; 9; 10; 11; 12; 16; 17; 18; 19; 20; 22; 25; ...,"{8: 1, 9: 4, 10: 1, 11: 1, 12: 1, 16: 1, 17: 1...",yg9ye3i2; kjfqdfen; nnhf3crw; 5p00bwej; o19kew...
3,Covid 19,57151,27964,735,2.043735,77.756463,19; 31; 32; 33; 34; 35; 36; 37; 38; 39; 40; 41...,"{19: 2, 31: 1, 32: 18, 33: 18, 34: 20, 35: 95,...",bktpj9vx; 96r5q6bn; 32uerbr0; gk12rmas; 1uaaxv...
4,CoV 2 infection,44265,28863,742,1.533624,59.656334,10; 11; 14; 16; 17; 19; 20; 26; 31; 32; 33; 34...,"{10: 1, 11: 1, 14: 3, 16: 1, 17: 5, 19: 5, 20:...",829cy3xl; isy9ov2c; tya76tgm; jxj5aqgj; 5vmt4e...
...,...,...,...,...,...,...,...,...,...
1504,Covid 19 Virus infection,1,1,1,1.000000,1.000000,197,{197: 1},ihvnipph
1505,infection caused by nCoV,1,1,1,1.000000,1.000000,374,{374: 1},vn60aofb
1506,Coronavirus disease (COVID 19) caused by SARS ...,1,1,1,1.000000,1.000000,199,{199: 1},2bexzycy
1507,COVID 19 novel coronavirus disease,1,1,1,1.000000,1.000000,199,{199: 1},5k6eq3ri
1508,Coronavirus Severe Respiratory Syndrome,1,1,1,1.000000,1.000000,210,{210: 1},fnl2u1hj

In [18]:
new_file = pd.read_csv('analysis_Merged_results_/result_entities_Merged_results_.tsv',delimiter='\t',on_bad_lines='warn')
print(np.sum(new_file['total_count']))
new_file

1772810

,Unnamed: 0,total_count,articles_spanned,batches_spanned,freq_per_article,freq_per_batch,batch_set,batch_count,articles_set
0,Disease,1191488,429672,763,2.773018,1561.583224,2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15...,"{2: 1, 3: 1, 4: 1, 5: 2, 6: 4, 7: 8, 8: 11, 9:...",qp7k5fz9; 6c04s94b; om2900sd; u9sdc080; ifqjhj...
1,Virus,531890,257715,758,2.063869,701.701847,2; 7; 8; 9; 10; 11; 12; 13; 14; 15; 16; 17; 18...,"{2: 2, 7: 8, 8: 10, 9: 12, 10: 19, 11: 32, 12:...",w0ni99rm; frox4uph; 79pjfhpt; 17g1jt8u; 7ati57...
2,Variant,45499,23363,765,1.947481,59.475817,0; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; ...,"{0: 48, 1: 57, 2: 60, 3: 40, 4: 43, 5: 36, 6: ...",0elmyq94; l5jeo692; 531jfjpc; jp8o4xzf; y3hdnw...
3,Mutation,3933,2381,625,1.651827,6.292800,10; 20; 26; 32; 37; 46; 48; 49; 52; 56; 58; 63...,"{10: 1, 20: 1, 26: 1, 32: 2, 37: 1, 46: 5, 48:...",y0smhyg5; ehpq0mvm; 2ocoh97e; iu6egrck; 3gmazp...

In [23]:
new_file = pd.read_csv('analysis_merged_separately/analysis_merged_Disease/result_entities_merged_Disease.tsv',delimiter='\t',on_bad_lines='warn')
print(np.sum(new_file['total_count']))
new_file

1610695

,Unnamed: 0,total_count,articles_spanned,batches_spanned,freq_per_article,freq_per_batch,batch_set,batch_count,articles_set
0,COVID 19,1168839,377771,754,3.094041,1550.184350,7; 8; 9; 10; 11; 12; 13; 14; 15; 16; 17; 18; 1...,"{7: 4, 8: 11, 9: 30, 10: 37, 11: 31, 12: 49, 1...",lxq6af3h; g3azf2jd; zv6s90if; ldneuqms; j5s62o...
1,coronavirus disease,74663,69357,748,1.076503,99.816845,8; 9; 10; 11; 12; 14; 16; 17; 18; 19; 20; 22; ...,"{8: 1, 9: 4, 10: 1, 11: 3, 12: 2, 14: 2, 16: 1...",n3kddmdx; g3azf2jd; jnlj1qqm; 1radg22k; c5g2xq...
2,coronavirus disease 2019,58002,53739,746,1.079328,77.750670,8; 9; 10; 11; 12; 16; 17; 18; 19; 20; 22; 25; ...,"{8: 1, 9: 4, 10: 1, 11: 1, 12: 1, 16: 1, 17: 1...",n3kddmdx; g3azf2jd; jnlj1qqm; c5g2xq2e; glqm4y...
3,Covid 19,57151,27964,735,2.043735,77.756463,19; 31; 32; 33; 34; 35; 36; 37; 38; 39; 40; 41...,"{19: 2, 31: 1, 32: 18, 33: 18, 34: 20, 35: 95,...",akls7fvp; 683zagdw; 5fe8rmhm; mdkt6rez; 2nt70m...
4,CoV 2 infection,44265,28863,742,1.533624,59.656334,10; 11; 14; 16; 17; 19; 20; 26; 31; 32; 33; 34...,"{10: 1, 11: 1, 14: 3, 16: 1, 17: 5, 19: 5, 20:...",2cglkidv; glqm4ypx; qalficgu; kritn0ox; j5s62o...
...,...,...,...,...,...,...,...,...,...
1504,POST COVID19,1,1,1,1.000000,1.000000,757,{757: 1},2166mm9b
1505,covid 19 infectious diseases,1,1,1,1.000000,1.000000,756,{756: 1},w1qirnry
1506,infectious pneumonia caused by severe acute re...,1,1,1,1.000000,1.000000,746,{746: 1},8mxge0ax
1507,infection caused by Novel Coronavirus,1,1,1,1.000000,1.000000,739,{739: 1},n7ylgqfu
1508,Disease (COVID 19) caused by Novel Coronavirus,1,1,1,1.000000,1.000000,739,{739: 1},aouhawgx

In [24]:
new_file = pd.read_csv('analysis_merged_separately/analysis_merged_Virus/result_entities_merged_Virus.tsv',delimiter='\t',on_bad_lines='warn')
print(np.sum(new_file['total_count']))
new_file

848179

,Unnamed: 0,total_count,articles_spanned,batches_spanned,freq_per_article,freq_per_batch,batch_set,batch_count,articles_set
0,SARS CoV 2,350581,130133,748,2.694021,468.691176,8; 9; 10; 11; 12; 13; 14; 16; 17; 19; 20; 23; ...,"{8: 1, 9: 4, 10: 12, 11: 21, 12: 2, 13: 2, 14:...",onwvtyao; ldjugbpj; n1hb9qzn; 69wlemym; cy74m1...
1,coronavirus,204183,144329,756,1.414705,270.083333,2; 7; 8; 9; 10; 11; 12; 14; 15; 16; 17; 18; 19...,"{2: 2, 7: 3, 8: 2, 9: 5, 10: 8, 11: 6, 12: 3, ...",lwnkubnz; wc8a4v46; 4t2i53ri; xp7rwy4g; 01ep5c...
2,Coronavirus,42346,37125,747,1.140633,56.688086,8; 9; 11; 12; 19; 20; 22; 23; 26; 27; 28; 29; ...,"{8: 3, 9: 3, 11: 1, 12: 1, 19: 2, 20: 5, 22: 2...",wt6taz2y; a4jsvdhe; m5y5kdac; be4e9isy; t8tf5k...
3,acute respiratory syndrome coronavirus 2,37771,36654,743,1.030474,50.835801,10; 11; 12; 16; 19; 20; 22; 23; 30; 31; 32; 33...,"{10: 2, 11: 1, 12: 1, 16: 1, 19: 4, 20: 6, 22:...",3ki2uxru; n1hb9qzn; u8vwpaet; pfiwgkcc; k7k6x6...
4,severe acute respiratory syndrome coronavirus 2,32566,31622,742,1.029853,43.889488,10; 11; 12; 16; 19; 20; 22; 30; 31; 32; 33; 34...,"{10: 1, 11: 1, 12: 1, 16: 1, 19: 4, 20: 3, 22:...",3ki2uxru; n1hb9qzn; k7k6x6ls; iaa5s3tz; imyoje...
...,...,...,...,...,...,...,...,...,...
611,severe acute respiratory Syndrome Coronavirus 2,1,1,1,1.000000,1.000000,486,{486: 1},lyigqxry
612,acute respiratory Syndrome Coronavirus 2,1,1,1,1.000000,1.000000,486,{486: 1},lyigqxry
613,SARS COV 2 VIRUS,1,1,1,1.000000,1.000000,489,{489: 1},vfv7in7q
614,COV 2 VIRUS,1,1,1,1.000000,1.000000,489,{489: 1},vfv7in7q
615,CORONavirus,1,1,1,1.000000,1.000000,498,{498: 1},4af86t6f

In [25]:
new_file = pd.read_csv('analysis_merged_separately/analysis_merged_Virus/result_entities_merged_Virus.tsv',delimiter='\t',on_bad_lines='warn')
print(np.sum(new_file['total_count']))
new_file

848179

,Unnamed: 0,total_count,articles_spanned,batches_spanned,freq_per_article,freq_per_batch,batch_set,batch_count,articles_set
0,SARS CoV 2,350581,130133,748,2.694021,468.691176,8; 9; 10; 11; 12; 13; 14; 16; 17; 19; 20; 23; ...,"{8: 1, 9: 4, 10: 12, 11: 21, 12: 2, 13: 2, 14:...",onwvtyao; ldjugbpj; n1hb9qzn; 69wlemym; cy74m1...
1,coronavirus,204183,144329,756,1.414705,270.083333,2; 7; 8; 9; 10; 11; 12; 14; 15; 16; 17; 18; 19...,"{2: 2, 7: 3, 8: 2, 9: 5, 10: 8, 11: 6, 12: 3, ...",lwnkubnz; wc8a4v46; 4t2i53ri; xp7rwy4g; 01ep5c...
2,Coronavirus,42346,37125,747,1.140633,56.688086,8; 9; 11; 12; 19; 20; 22; 23; 26; 27; 28; 29; ...,"{8: 3, 9: 3, 11: 1, 12: 1, 19: 2, 20: 5, 22: 2...",wt6taz2y; a4jsvdhe; m5y5kdac; be4e9isy; t8tf5k...
3,acute respiratory syndrome coronavirus 2,37771,36654,743,1.030474,50.835801,10; 11; 12; 16; 19; 20; 22; 23; 30; 31; 32; 33...,"{10: 2, 11: 1, 12: 1, 16: 1, 19: 4, 20: 6, 22:...",3ki2uxru; n1hb9qzn; u8vwpaet; pfiwgkcc; k7k6x6...
4,severe acute respiratory syndrome coronavirus 2,32566,31622,742,1.029853,43.889488,10; 11; 12; 16; 19; 20; 22; 30; 31; 32; 33; 34...,"{10: 1, 11: 1, 12: 1, 16: 1, 19: 4, 20: 3, 22:...",3ki2uxru; n1hb9qzn; k7k6x6ls; iaa5s3tz; imyoje...
...,...,...,...,...,...,...,...,...,...
611,severe acute respiratory Syndrome Coronavirus 2,1,1,1,1.000000,1.000000,486,{486: 1},lyigqxry
612,acute respiratory Syndrome Coronavirus 2,1,1,1,1.000000,1.000000,486,{486: 1},lyigqxry
613,SARS COV 2 VIRUS,1,1,1,1.000000,1.000000,489,{489: 1},vfv7in7q
614,COV 2 VIRUS,1,1,1,1.000000,1.000000,489,{489: 1},vfv7in7q
615,CORONavirus,1,1,1,1.000000,1.000000,498,{498: 1},4af86t6f