In [4]:
import pandas as pd
import numpy as np
import os

print(os.path.exists("analysis_covid-19/result_entities_covid-19.tsv"))

new_file = pd.read_csv('analysis_covid-19/result_entities_covid-19.tsv',delimiter='\t',on_bad_lines='warn')
print(np.sum(new_file['total_count']))
new_file

True
1610695

,Unnamed: 0,total_count,articles_spanned,batches_spanned,freq_per_article,freq_per_batch,batch_set,batch_count,articles_set
0,COVID 19,1168839,377771,754,3.094041,1550.184350,7; 8; 9; 10; 11; 12; 13; 14; 15; 16; 17; 18; 1...,"{7: 4, 8: 11, 9: 30, 10: 37, 11: 31, 12: 49, 1...",829cy3xl; qpf52vrx; lzd9lil6; n9pfxv7d; zyn8p6...
1,coronavirus disease,74663,69357,748,1.076503,99.816845,8; 9; 10; 11; 12; 14; 16; 17; 18; 19; 20; 22; ...,"{8: 1, 9: 4, 10: 1, 11: 3, 12: 2, 14: 2, 16: 1...",yg9ye3i2; kjfqdfen; nnhf3crw; 5p00bwej; o19kew...
2,coronavirus disease 2019,58002,53739,746,1.079328,77.750670,8; 9; 10; 11; 12; 16; 17; 18; 19; 20; 22; 25; ...,"{8: 1, 9: 4, 10: 1, 11: 1, 12: 1, 16: 1, 17: 1...",yg9ye3i2; kjfqdfen; nnhf3crw; 5p00bwej; o19kew...
3,Covid 19,57151,27964,735,2.043735,77.756463,19; 31; 32; 33; 34; 35; 36; 37; 38; 39; 40; 41...,"{19: 2, 31: 1, 32: 18, 33: 18, 34: 20, 35: 95,...",bktpj9vx; 96r5q6bn; 32uerbr0; gk12rmas; 1uaaxv...
4,CoV 2 infection,44265,28863,742,1.533624,59.656334,10; 11; 14; 16; 17; 19; 20; 26; 31; 32; 33; 34...,"{10: 1, 11: 1, 14: 3, 16: 1, 17: 5, 19: 5, 20:...",829cy3xl; isy9ov2c; tya76tgm; jxj5aqgj; 5vmt4e...
...,...,...,...,...,...,...,...,...,...
1504,Covid 19 Virus infection,1,1,1,1.000000,1.000000,197,{197: 1},ihvnipph
1505,infection caused by nCoV,1,1,1,1.000000,1.000000,374,{374: 1},vn60aofb
1506,Coronavirus disease (COVID 19) caused by SARS ...,1,1,1,1.000000,1.000000,199,{199: 1},2bexzycy
1507,COVID 19 novel coronavirus disease,1,1,1,1.000000,1.000000,199,{199: 1},5k6eq3ri
1508,Coronavirus Severe Respiratory Syndrome,1,1,1,1.000000,1.000000,210,{210: 1},fnl2u1hj

In [5]:
import pandas as pd
import numpy as np

new_file = pd.read_csv('analysis_Sars_cov2/result_entities_Sars_cov2.tsv',delimiter='\t',on_bad_lines='warn')
print(np.sum(new_file['total_count']))
new_file

848179

,Unnamed: 0,total_count,articles_spanned,batches_spanned,freq_per_article,freq_per_batch,batch_set,batch_count,articles_set
0,SARS CoV 2,350581,130133,748,2.694021,468.691176,8; 9; 10; 11; 12; 13; 14; 16; 17; 19; 20; 23; ...,"{8: 1, 9: 4, 10: 12, 11: 21, 12: 2, 13: 2, 14:...",8wrrkey2; 2q6oa74f; ltjf59d4; bmeqsqpm; za1pqv...
1,coronavirus,204183,144329,756,1.414705,270.083333,2; 7; 8; 9; 10; 11; 12; 14; 15; 16; 17; 18; 19...,"{2: 2, 7: 3, 8: 2, 9: 5, 10: 8, 11: 6, 12: 3, ...",bo0zx77d; 8wrrkey2; 2q6oa74f; 0qjuux1s; na23jw...
2,Coronavirus,42346,37125,747,1.140633,56.688086,8; 9; 11; 12; 19; 20; 22; 23; 26; 27; 28; 29; ...,"{8: 3, 9: 3, 11: 1, 12: 1, 19: 2, 20: 5, 22: 2...",g6i3x433; za1pqvvz; 6tnkz6hh; mezr6vw2; ygkgkk...
3,acute respiratory syndrome coronavirus 2,37771,36654,743,1.030474,50.835801,10; 11; 12; 16; 19; 20; 22; 23; 30; 31; 32; 33...,"{10: 2, 11: 1, 12: 1, 16: 1, 19: 4, 20: 6, 22:...",hfgay0u1; ckcb4m3f; na23jwd1; 2q6oa74f; za1pqv...
4,severe acute respiratory syndrome coronavirus 2,32566,31622,742,1.029853,43.889488,10; 11; 12; 16; 19; 20; 22; 30; 31; 32; 33; 34...,"{10: 1, 11: 1, 12: 1, 16: 1, 19: 4, 20: 3, 22:...",hfgay0u1; ckcb4m3f; na23jwd1; za1pqvvz; vjubia...
...,...,...,...,...,...,...,...,...,...
611,SARs cov 2,1,1,1,1.000000,1.000000,192,{192: 1},07r7inis
612,new COronaVIrus,1,1,1,1.000000,1.000000,192,{192: 1},8w28avgl
613,Novel COV,1,1,1,1.000000,1.000000,194,{194: 1},wkpfbhqm
614,Sars Cov 2 Virus,1,1,1,1.000000,1.000000,343,{343: 1},apa2uaf0
615,SARs Cov 2 virus,1,1,1,1.000000,1.000000,760,{760: 1},yr9xa0wm

In [7]:
import pandas as pd
import numpy as np

new_file = pd.read_csv('analysis_SarsCov2_variant/result_entities_SarsCov2_variant.tsv',delimiter='\t',on_bad_lines='warn')
print(np.sum(new_file['total_count']))
new_file

80825

,Unnamed: 0,total_count,articles_spanned,batches_spanned,freq_per_article,freq_per_batch,batch_set,batch_count,articles_set
0,Omicron,8764,2555,649,3.430137,13.503852,20; 26; 54; 55; 56; 58; 59; 63; 64; 66; 71; 75...,"{20: 2, 26: 6, 54: 14, 55: 1, 56: 2, 58: 1, 59...",m9koi4m7; 5ogges89; w8b7iycb; 4zunfua0; ir7ed6...
1,Delta,8484,3662,700,2.316767,12.120000,1; 2; 3; 4; 7; 10; 11; 12; 13; 17; 18; 20; 24;...,"{1: 4, 2: 2, 3: 1, 4: 3, 7: 2, 10: 1, 11: 1, 1...",ner59i85; l413d2ze; m9koi4m7; w23g30v8; n1f8lh...
2,alpha,7343,5061,762,1.450899,9.636483,0; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; ...,"{0: 15, 1: 13, 2: 20, 3: 8, 4: 12, 5: 7, 6: 15...",2a6jo7ux; w6yijckh; py73a6or; gn34m0hb; j55d2q...
3,beta,6832,4650,762,1.469247,8.965879,0; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; ...,"{0: 14, 1: 17, 2: 11, 3: 5, 4: 8, 5: 25, 6: 11...",s06nd4gm; 47x11l9r; ypsbvm6a; 7sfo0hio; kx85z6...
4,gamma,3856,2703,729,1.426563,5.289438,0; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; ...,"{0: 12, 1: 14, 2: 12, 3: 12, 4: 9, 5: 7, 6: 7,...",m3fygp8w; jn313bsx; iwiyxrpy; ctv4xspf; rh1dv0...
...,...,...,...,...,...,...,...,...,...
991,B.1.139,1,1,1,1.000000,1.000000,536,{536: 1},s15iuk3i
992,variant Hb,1,1,1,1.000000,1.000000,533,{533: 1},t6n95laz
993,B.1.218,1,1,1,1.000000,1.000000,175,{175: 1},4kqhtxhn
994,B.1.260,1,1,1,1.000000,1.000000,175,{175: 1},4kqhtxhn
995,B.1.1.7 Lineage,1,1,1,1.000000,1.000000,762,{762: 1},thq0ejl5

In [6]:
new_file = pd.read_csv('analysis_SarsCov2_mutation/result_entities_SarsCov2_mutation.tsv',delimiter='\t',on_bad_lines='warn')
print(np.sum(new_file['total_count']))
new_file

5786

,Unnamed: 0,total_count,articles_spanned,batches_spanned,freq_per_article,freq_per_batch,batch_set,batch_count,articles_set
0,D614G,2092,1319,554,1.586050,3.776173,10; 32; 37; 46; 49; 52; 56; 58; 63; 92; 95; 10...,"{10: 1, 32: 2, 37: 1, 46: 5, 49: 1, 52: 1, 56:...",c1xjauvt; gxpub1a8; rkr0m3js; as4k6xiu; 2rnt5i...
1,N501Y,1280,744,413,1.720430,3.099274,48; 49; 56; 85; 86; 87; 117; 132; 133; 139; 14...,"{48: 3, 49: 1, 56: 1, 85: 1, 86: 2, 87: 3, 117...",pn3jda9t; ckqi8m2e; 2i8fh05m; z0qds22k; hf80lv...
2,L452R,492,281,209,1.750890,2.354067,514; 517; 518; 525; 527; 529; 531; 532; 533; 5...,"{48: 1, 49: 1, 85: 3, 144: 1, 147: 5, 151: 3, ...",aahlebht; 9c67oha0; so2ryrbu; ckqi8m2e; ufgl0q...
3,K417N,361,260,204,1.388462,1.769608,513; 514; 516; 517; 518; 521; 522; 527; 528; 5...,"{48: 2, 87: 2, 133: 1, 146: 1, 150: 2, 151: 1,...",wqt6njut; o5euo2yq; 9c67oha0; zvioavyx; so2ryr...
4,E484Q,170,105,95,1.619048,1.789474,518; 527; 529; 531; 532; 536; 539; 543; 553; 5...,"{85: 3, 146: 1, 147: 1, 151: 1, 153: 1, 157: 2...",kl7jt6dt; 9c67oha0; ckqi8m2e; bkp35usq; afvdr3...
5,P681H,140,101,90,1.386139,1.555556,516; 519; 521; 531; 532; 533; 535; 538; 539; 5...,"{143: 1, 146: 1, 149: 1, 160: 2, 168: 1, 179: ...",9c67oha0; gbvpvqzi; kwnegjyt; ltxsyyob; 0s6efz...
6,P681R,133,90,85,1.477778,1.564706,516; 517; 529; 531; 20; 532; 534; 539; 543; 55...,"{20: 1, 144: 2, 146: 1, 151: 1, 153: 1, 154: 2...",9c67oha0; ckqi8m2e; zq8o41l3; immehelw; a2btka...
7,S477N,127,94,82,1.351064,1.548780,513; 514; 518; 520; 523; 535; 539; 540; 549; 5...,"{143: 1, 158: 1, 159: 1, 162: 1, 166: 1, 175: ...",h93g164s; fiq5rkl0; so2ryrbu; 9hwqro99; 02s1rd...
8,Y453F,77,56,50,1.375000,1.540000,514; 642; 266; 523; 655; 659; 151; 539; 159; 5...,"{151: 1, 159: 1, 184: 2, 186: 2, 210: 1, 237: ...",vyjnagtm; so2ryrbu; ufgl0qu7; 90gmfawi; 0x5ln5...
9,E484K,61,54,52,1.129630,1.173077,642; 516; 646; 649; 527; 147; 659; 665; 538; 5...,"{87: 1, 147: 1, 169: 1, 170: 1, 176: 1, 220: 1...",45e10fgt; q0o46uej; bwi47ebs; e45eli19; 9bhi3r...
10,K417T,50,45,39,1.111111,1.282051,513; 514; 645; 647; 527; 528; 531; 148; 405; 6...,"{148: 1, 239: 1, 242: 1, 286: 1, 287: 1, 295: ...",k8qcabr6; co6qdzuc; fyjs90ih; coj34ybh; vk22bq...
11,K417N/T,47,42,41,1.119048,1.146341,641; 514; 518; 268; 528; 274; 539; 667; 541; 2...,"{159: 1, 198: 1, 268: 1, 274: 1, 286: 2, 323: ...",bwi47ebs; zvioavyx; so2ryrbu; h7uopq0a; 8xablk...
12,S494P,47,34,32,1.382353,1.468750,513; 642; 261; 518; 392; 522; 145; 658; 659; 5...,"{145: 6, 170: 1, 200: 1, 261: 1, 305: 1, 314: ...",nhtnyn7b; k8qcabr6; akpzqctu; r1rzl9sl; 8bxune...
13,Q493R,44,38,38,1.157895,1.157895,513; 258; 520; 266; 529; 659; 152; 666; 290; 2...,"{152: 1, 170: 1, 172: 1, 258: 1, 266: 1, 290: ...",wqt6njut; 5mjiintq; sisiw6n7; u9a7jcnb; y0xedc...
14,Q675H,42,14,13,3.000000,3.230769,261; 167; 552; 555; 717; 671; 306; 466; 214; 4...,"{167: 1, 214: 10, 261: 1, 280: 10, 306: 1, 380...",solhlf8p; 8bxuneo6; n8lc3aad; 3rvikpl8; lkmwni...
15,A570D,40,38,37,1.052632,1.081081,259; 637; 390; 266; 143; 403; 541; 547; 677; 1...,"{143: 1, 166: 1, 168: 1, 183: 1, 219: 1, 259: ...",jezkk6st; jfy0lxuv; ge5q5s8q; bjj8wp9y; lgl5mq...
16,G142D,40,25,24,1.600000,1.666667,515; 517; 518; 263; 527; 146; 279; 26; 539; 16...,"{26: 1, 146: 2, 164: 1, 182: 1, 218: 2, 249: 2...",ypwoa9w0; rv2evb6k; 8fiswlb2; 7lkadwje; zuudv0...
17,T95I,40,32,30,1.250000,1.333333,513; 517; 263; 527; 534; 538; 283; 159; 171; 5...,"{159: 3, 171: 1, 193: 1, 195: 2, 198: 1, 210: ...",ci8zh735; rl2rbz7e; 8gqt3mhs; y0xedcpd; 3vfyk6...
18,L18F,32,29,29,1.103448,1.103448,257; 514; 261; 648; 267; 541; 286; 552; 169; 5...,"{169: 1, 180: 1, 257: 1, 261: 2, 267: 1, 286: ...",8bxuneo6; zmtqthpr; fok1eadx; 01ky02je; 5r9o0c...
19,Q498R,32,26,26,1.230769,1.230769,513; 529; 537; 672; 162; 290; 548; 684; 557; 1...,"{162: 1, 181: 1, 290: 1, 323: 2, 343: 1, 355: ...",g4ul6fuw; sisiw6n7; y0xedcpd; g9jxg37i; xodw74...
20,E484A,29,24,24,1.208333,1.208333,520; 658; 661; 535; 415; 557; 305; 183; 323; 5...,"{183: 1, 237: 1, 305: 1, 323: 1, 349: 1, 415: ...",22x7wipd; y0xedcpd; n2msxkod; q732eylh; zinhsp...
21,H655Y,29,24,24,1.208333,1.208333,640; 513; 521; 650; 652; 527; 286; 557; 558; 1...,"{180: 1, 286: 1, 340: 1, 381: 1, 448: 2, 455: ...",x093a6fm; y0xedcpd; 76xkhq9p; x48xjedg; x7kroa...
22,G446S,28,24,24,1.166667,1.166667,258; 531; 535; 291; 419; 548; 675; 557; 305; 5...,"{237: 1, 258: 1, 291: 1, 305: 1, 323: 1, 343: ...",22x7wipd; bsa2g84l; y0xedcpd; 49nhfymh; sx1oge...
23,F490S,27,25,24,1.080000,1.125000,261; 529; 147; 150; 536; 669; 552; 437; 444; 1...,"{147: 1, 150: 1, 189: 1, 195: 1, 204: 1, 217: ...",zriw6fp2; 8bxuneo6; g74knxqm; wljvfln0; r60ked...
24,S371L,23,21,20,1.095238,1.150000,385; 258; 279; 290; 291; 548; 178; 181; 565; 3...,"{178: 1, 181: 1, 258: 1, 279: 1, 290: 1, 291: ...",g4ul6fuw; sisiw6n7; nzf83xwx; y0xedcpd; hbyxy4...
25,S375F,22,16,16,1.375000,1.375000,290; 258; 548; 580; 75; 493; 589; 305; 753; 18...,"{75: 1, 181: 1, 258: 1, 284: 3, 290: 1, 305: 2...",g4ul6fuw; sisiw6n7; 3amvizmd; f63adbqa; y0xedc...
26,S982A,22,20,20,1.100000,1.100000,259; 390; 143; 407; 677; 166; 168; 687; 314; 5...,"{143: 1, 166: 1, 168: 1, 259: 1, 314: 1, 380: ...",zwhe89zr; jfy0lxuv; m8tzx1vr; ge5q5s8q; qfveem...
27,G339D,22,16,16,1.375000,1.375000,672; 548; 580; 102; 581; 759; 237; 493; 305; 4...,"{102: 2, 237: 1, 305: 1, 379: 1, 435: 3, 467: ...",vf7vjor2; 22x7wipd; 4bdukagp; jyfrvnx5; f63adb...
28,D614 G,21,13,13,1.615385,1.615385,320; 673; 514; 579; 704; 739; 528; 625; 720; 5...,"{277: 1, 278: 1, 320: 5, 514: 1, 528: 1, 573: ...",xmlp2hmh; x6mqff34; l4hueltv; gbvpvqzi; dcwrek...
29,T716I,20,18,17,1.111111,1.176471,610; 611; 292; 390; 168; 426; 715; 717; 749; 1...,"{143: 1, 168: 1, 292: 1, 314: 1, 390: 2, 426: ...",n21ymz64; bjj8wp9y; 0ck5jzr9; w38bkis4; w2cyak...
30,D950N,18,17,17,1.058824,1.058824,515; 389; 631; 169; 521; 763; 559; 687; 146; 4...,"{20: 1, 146: 1, 169: 1, 249: 1, 287: 1, 389: 1...",0cotf8su; ypwoa9w0; bplqdcox; 2i8gsrnk; hh8uz4...
31,T19R,15,14,14,1.071429,1.071429,611; 631; 169; 171; 459; 717; 146; 501; 407; 3...,"{146: 1, 169: 1, 171: 1, 249: 1, 312: 1, 317: ...",ypwoa9w0; 8fiswlb2; f003x2ha; fvfy29nv; 5qvtdx...
32,Y505H,14,12,12,1.166667,1.166667,323; 548; 711; 523; 493; 557; 590; 726; 567; 5...,"{323: 1, 493: 1, 505: 1, 523: 1, 548: 1, 557: ...",y0xedcpd; t642vlty; zxbc4hnd; u1m6blu8; il15k5...
33,D1118H,14,14,14,1.000000,1.000000,579; 485; 168; 695; 715; 525; 749; 143; 750; 4...,"{143: 1, 168: 1, 314: 1, 380: 1, 469: 1, 485: ...",w2cyakqb; ge5q5s8q; w38bkis4; 2aslzgdk; lgl5mq...
34,S373P,14,14,14,1.000000,1.000000,258; 290; 548; 580; 493; 305; 753; 181; 475; 3...,"{181: 1, 258: 1, 290: 1, 305: 1, 343: 1, 379: ...",vf7vjor2; g4ul6fuw; sisiw6n7; f63adbqa; y0xedc...
35,G496S,12,11,11,1.090909,1.090909,355; 323; 548; 493; 557; 529; 181; 726; 343; 5...,"{181: 1, 323: 1, 343: 1, 355: 1, 493: 1, 505: ...",g4ul6fuw; y0xedcpd; t642vlty; u1m6blu8; hn1r8x...
36,P681H/R,12,2,2,6.000000,6.000000,205; 405,"{205: 6, 405: 6}",smzrzq21; 1yg51gkq
37,Q954H,12,10,9,1.200000,1.333333,580; 455; 493; 305; 465; 625; 279; 381; 575,"{279: 2, 305: 2, 381: 1, 455: 1, 465: 1, 493: ...",ra1cc4lm; ei6t54fd; x093a6fm; f63adbqa; y0xedc...
38,A701V,11,11,11,1.000000,1.000000,482; 322; 516; 712; 619; 591; 624; 688; 338; 1...,"{179: 1, 322: 1, 338: 1, 415: 1, 482: 1, 516: ...",q5qsdkea; 2rg93f7m; ak5pubvp; ocm76ij4; vc4ogd...
39,D215G,10,10,10,1.000000,1.000000,640; 162; 291; 619; 622; 591; 688; 750; 180; 340,"{162: 1, 180: 1, 291: 1, 340: 1, 591: 1, 619: ...",2aslzgdk; ckqi8m2e; 76xkhq9p; mugx1giy; ekj9ka...
40,D138Y,10,8,8,1.250000,1.250000,749; 718; 338; 179; 633; 314; 315; 286,"{179: 1, 286: 1, 314: 2, 315: 1, 338: 1, 633: ...",6noowoya; m7i0ovq9; q5qsdkea; 2rg93f7m; 7tapvk...
41,D796Y,9,7,7,1.285714,1.285714,455; 557; 625; 467; 630; 763; 381,"{381: 1, 455: 1, 467: 2, 557: 1, 625: 1, 630: ...",ra1cc4lm; n41xkgfu; x093a6fm; u1m6blu8; mbntzc...
42,D80A,7,7,7,1.000000,1.000000,322; 619; 591; 688; 146; 249; 415,"{146: 1, 249: 1, 322: 1, 415: 1, 591: 1, 619: ...",ocm76ij4; xfjix7hy; fdbfz5fj; rodw6t4i; r3tt5c...
43,R158G,7,6,6,1.166667,1.166667,517; 263; 116; 537; 604; 606,"{116: 1, 263: 1, 517: 1, 537: 1, 604: 2, 606: 1}",gycq858w; ypwoa9w0; h2x81m6a; yfz92fnj; gvemgs...
44,L981F,5,3,3,1.666667,1.666667,305; 580; 493,"{305: 2, 493: 1, 580: 2}",f63adbqa; y0xedcpd; n2msxkod
45,Y145del,4,4,4,1.000000,1.000000,248; 489; 523; 733,"{248: 1, 489: 1, 523: 1, 733: 1}",y6675ffu; h2x7928h; i00c2ylu; 2znoot8h
46,T1027I,4,4,4,1.000000,1.000000,630; 523; 286; 151,"{151: 1, 286: 1, 523: 1, 630: 1}",1oj3fx08; 425frdcu; 0pictywc; kal74gbx
47,N439K,3,3,3,1.000000,1.000000,329; 539; 617,"{329: 1, 539: 1, 617: 1}",892oxp65; kwnegjyt; 7r30p6s3
48,L212I,3,3,3,1.000000,1.000000,490; 557; 670,"{490: 1, 557: 1, 670: 1}",ix5piha1; u1m6blu8; yjos07sz
49,T20N,2,2,2,1.000000,1.000000,541; 286,"{286: 1, 541: 1}",1oj3fx08; d3b0jev1
50,P26S,2,2,2,1.000000,1.000000,541; 286,"{286: 1, 541: 1}",1oj3fx08; d3b0jev1
51,R190S,2,2,2,1.000000,1.000000,640; 286,"{286: 1, 640: 1}",1oj3fx08; s0374olh
52,N440K,2,2,2,1.000000,1.000000,289; 685,"{289: 1, 685: 1}",zxwd8kzb; 40pyeh7e
53,T478K,2,2,2,1.000000,1.000000,536; 553,"{536: 1, 553: 1}",wljvfln0; 5dk6tlhg
54,ORF1b:P314L,1,1,1,1.000000,1.000000,286,{286: 1},1oj3fx08
55,A243del,1,1,1,1.000000,1.000000,640,{640: 1},s0374olh